baseURL = "https://www.mlosun.com/"
languageCode = "zh-cn"
defaultContentLanguage = "zh-cn"
title = "洛森博客"                         # site title  # 网站标题
theme = "zozo"
hasCJKLanguage = true                  # has chinese/japanese/korean ?  # 自动检测是否包含 中文\日文\韩文
summaryLength = 100
paginate = 4                           # shows the number of articles  # 首页显示文章数量
enableEmoji = true
googleAnalytics = "UA-175449293-1"                   # your google analytics id
disqusShortname = ""                   # your discuss shortname

pygmentsUseClasses = true
pygmentCodeFences = true
pygmentscodefencesguesssyntax = true

[author]                               # essential                     # 必需
  name = "洛森"

[blackfriday]
  smartypants = false

[[menu.main]]                          # config your menu  # 配置菜单
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "Archive"
  weight = 20
  identifier = "archive"
  url = "/posts/"
[[menu.main]]
  name = "Tags"
  weight = 30
  identifier = "tags"
  url = "/tags/"
[[menu.main]]
  name = "About"
  weight = 40
  identifier = "about"
  url = "/about/"

[params]
  subTitle = "念念不忘,必有回响"                                       # site's subTitle  # 网站二级标题
  footerSlogan = "念念不忘,必有回响"                                   # site's footer slogan  # 网站页脚标语
  keywords = ["洛森博客","博客","mlosun"]                                  # site's keywords  # 网站关键字
  description = "洛森的个人博客｜念念不忘,必有回响"                        # site's description  # 网站描述
  enableMathJax = true                                                 # enable mathjax  # 是否使用mathjax（数学公式）
  enableSummary = true                                                 # display the article summary  # 是否显示文章摘要
  mainSections = ["posts","post"]
  
# Valine.
# You can get your appid and appkey from https://leancloud.cn
# more info please open https://valine.js.org
[params.valine]
  enable = true
  appId = "x3OniavxUWEtE0kPmFKr2Tz0-9Nh9j0Va"
  appKey = "1g8MfC9uH4tEg9OkXXusHTT1"
  placeholder = "期待你一针见血的评论，Come on！"
  visitor = true

# Your socail's url
[social]
#  github = " "
#  twitter = " "
#  facebook = " "
#  weibo = " "
#  instagram = " "

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true
